services:
    server:
      image: php:alpine
      volumes:
        - ./server:/home/app
      ports:
        - 127.0.0.1:8080:8080
      command: ["php", "-S", "0.0.0.0:8080"]
      working_dir: /home/app